### ISSUE TITLE
Win scroll bar

### ISSUE THREAD

**Issue by t7yang** [scottcorgan/focus-ui#1]
Please fix scroll bar on Windows:
![2016-12-30_155919](https://cloud.githubusercontent.com/assets/4502661/21561568/1164ae58-cea9-11e6-84c1-212ce4bdac51.png)

**Comment by scottcorgan** [comment]
What version are you using?

**Comment by t7yang** [comment]
latest 2.2.0

**Comment by scottcorgan** [comment]
Can you try latest master with `apm install https://github.com/scottcorgan/focus-ui`. There's a fix from `atom-dark-ui` theme that should make it a bit better.

Also. Is the issue that there is a scrollbar or that the scrollbar is out of place?

**Comment by t7yang** [comment]
problem solve with the master branch.
