### ISSUE TITLE
Deprecated selector in `focus-ui/index.less`

### ISSUE THREAD

**Issue by isu17** [scottcorgan/focus-ui#6]
In `focus-ui/index.less`: 

Starting from Atom v1.13.0, the contents of `atom-text-editor` elements are no longer encapsulated within a shadow DOM boundary. This means you should stop using `:host` and `::shadow` pseudo-selectors, and prepend all your syntax selectors with `syntax--`. To prevent breakage with existing style sheets, Atom will automatically upgrade the following selectors:

* `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini]::shadow .placeholder-text` => `atom-text-editor[mini] .placeholder-text,
atom-text-editor[mini].editor .placeholder-text`

* `atom-text-editor[mini] .selection .region,
atom-text-editor[mini]::shadow .selection .region` => `atom-text-editor[mini] .selection .region,
atom-text-editor[mini].editor .selection .region`

* `.atom-text-editor .line[class*="highlight-line-multi-line-solid-bottom"],
:host .line[class*="highlight-line-multi-line-solid-bottom"],
atom-text-editor .line[class*="highlight-line-multi-line-solid-bottom"],
atom-text-editor::shadow .line[class*="highlight-line-multi-line-solid-bottom"]` => `.atom-text-editor .line[class*="highlight-line-multi-line-solid-bottom"],
:host .line[class*="highlight-line-multi-line-solid-bottom"],
atom-text-editor .line[class*="highlight-line-multi-line-solid-bottom"],
atom-text-editor.editor .line[class*="highlight-line-multi-line-solid-bottom"]`

* `atom-text-editor::shadow .gutter` => `atom-text-editor.editor .gutter`

* `atom-text-editor::shadow .gutter .cursor-line` => `atom-text-editor.editor .gutter .cursor-line`

Automatic translation of selectors will be removed in a few release cycles to minimize startup time. Please, make sure to upgrade the above selectors as soon as possible.

**Comment by scottcorgan** [comment]
❓  Is this an automated issue, or is this something you're actually interested in getting fixed?

**Comment by isu17** [comment]
sorry, its automated, didnt know I did this
